---
title: "Klasyfikacja"
author: "Łukasz Wawrowski"
date: '2022-06-05'
output: html_document
---

# Wczytanie danych

```{r}
library(tidyverse)
library(readxl)

credit <- read_xlsx("data/german_credit_data.xlsx")

credit <- janitor::clean_names(credit)

credit <- credit %>% 
  mutate_if(is.character, as.factor)

credit <- credit %>% 
  mutate(job=as.factor(job))

credit <- VIM::kNN(data = credit, k = 1, imp_var = FALSE)

credit <- credit %>% 
  mutate(installment=credit_amount/duration)

summary(credit)
```

# Podział danych

```{r}
library(rsample)

set.seed(123)
credit_split <- validation_split(data = credit, prop = 0.75, strata = "risk")

credit_train <- training(credit_split$splits[[1]])
credit_test <- assessment(credit_split$splits[[1]])

save(credit_train, credit_test, file = "data/credit_train_test.rda")

load("data/credit_train_test.rda")

table(credit_train$risk)
table(credit_test$risk)

```

# Drzewa decyzyjne

```{r}
library(rpart)
library(rpart.plot)
library(caret)

m1 <- rpart(formula = risk ~ ., data = credit_train)

rpart.plot(m1)
```

```{r}
credit_risk_m1_train <- predict(m1, credit_train, type="class")

table(credit_train$risk, credit_risk_m1_train)

confusionMatrix(data = credit_risk_m1_train, reference = credit_train$risk, positive = "good", mode = "everything")
```

```{r}
credit_risk_m1_test <- predict(m1, credit_test, type="class")

confusionMatrix(data = credit_risk_m1_test, reference = credit_test$risk, positive = "good", mode = "everything")
159*(3500*0.2)-16*(3500*0.5)
```

# Lasy losowe

```{r}
library(ranger)

m2 <- ranger(formula = risk ~ ., data = credit_train, num.trees = 10)
```

```{r}
credit_risk_m2_train <- predict(m2, credit_train)

confusionMatrix(data = credit_risk_m2_train$predictions, reference = credit_train$risk, positive = "good", mode = "everything")
```

```{r}
credit_risk_m2_test <- predict(m2, credit_test)

confusionMatrix(data = credit_risk_m2_test$predictions, reference = credit_test$risk, positive = "good", mode = "everything")
145*(3500*0.2)-30*(3500*0.5)
```

# Gradient boosting

```{r}
library(h2o)

h2o.init()

# h2o.flow()

credit_train_h2o <- as.h2o(credit_train)
credit_test_h2o <- as.h2o(credit_test)

x_vars <- names(credit_train)[-10]
x_vars

m3 <- h2o.gbm(x = x_vars, y = "risk", training_frame = credit_train_h2o, validation_frame = credit_test_h2o)

m3
```

```{r}
credit_risk_m3_train <- as.data.frame(h2o.predict(m3, credit_train_h2o))

confusionMatrix(data = credit_risk_m3_train$predict, reference = credit_train$risk, positive = "good", mode = "everything")
```

```{r}
credit_risk_m3_test <- as.data.frame(h2o.predict(m3, credit_test_h2o))

confusionMatrix(data = credit_risk_m3_test$predict, reference = credit_test$risk, positive = "good", mode = "everything")
168*(3500*0.2)-7*(3500*0.5)
```

## walidacja krzyżowa

```{r}
m4 <- h2o.gbm(x = x_vars, y = "risk", training_frame = credit_train_h2o, nfolds = 5)
m4
```

# optymilizacja hiperparametrów

```{r}
gbm_params <- list(learn_rate = seq(0.01, 0.1, 0.01),
                    max_depth = seq(2, 10, 1),
                    sample_rate = seq(0.5, 1.0, 0.1),
                    col_sample_rate = seq(0.1, 1.0, 0.1),
                    ntrees = seq(50,150,10))

search_criteria <- list(strategy = "RandomDiscrete", max_models = 15, seed = 1)

gbm_grid <- h2o.grid(algorithm = "gbm", 
                      x = x_vars, 
                      y = "risk",
                      grid_id = "gbm_grid1",
                      training_frame = credit_train_h2o,
                      validation_frame = credit_test_h2o,
                      seed = 1,
                      hyper_params = gbm_params,
                      search_criteria = search_criteria)

gbm_gridperf <- h2o.getGrid(grid_id = "gbm_grid1",
                            sort_by = "auc",
                            decreasing = TRUE)

m5 <- h2o.getModel(gbm_gridperf@model_ids[[1]])
```

```{r}
credit_risk_m5_train <- as.data.frame(h2o.predict(m5, credit_train_h2o))

confusionMatrix(data = credit_risk_m5_train$predict, reference = credit_train$risk, positive = "good", mode = "everything")
```

```{r}
credit_risk_m5_test <- as.data.frame(h2o.predict(m5, credit_test_h2o))

confusionMatrix(data = credit_risk_m5_test$predict, reference = credit_test$risk, positive = "good", mode = "everything")

168*(3500*0.2)-7*(3500*0.5)
```

# krzywa roc

```{r}
plot(h2o.performance(m5, valid = T), type = "roc")
```

# ważność cech

```{r}
h2o.varimp(m5)
```

# pdp

```{r}
h2o.partialPlot(object = m5, data = credit_test_h2o, cols = "credit_amount")
```

```{r}
h2o.partialPlot(object = m5, data = credit_test_h2o, cols = "purpose")
```

