---
title: "Klasyfikacja"
author: "Łukasz Wawrowski"
date: "2023-05-13"
output: html_document
---

# Wczytanie danych

```{r}
library(tidyverse)
library(readxl)

credit <- read_xlsx("data/german_credit_data.xlsx")

# czyszczenie nazw kolumn
credit <- janitor::clean_names(credit)

credit <- credit %>% 
  mutate_if(is.character, as.factor)

credit <- credit %>% 
  mutate(job=as.factor(job))

credit <- VIM::kNN(data = credit, k = 1, imp_var = FALSE)

credit <- credit %>% 
  mutate(installment=credit_amount/duration)

summary(credit)

```

```{r}
credit <- read_xlsx("data/german_credit_data.xlsx") %>% 
  janitor::clean_names(.) %>% 
  mutate_if(is.character, as.factor) %>% 
  mutate(job=as.factor(job)) %>% 
  VIM::kNN(data = ., k = 1, imp_var = FALSE) %>% 
  mutate(installment=credit_amount/duration)

```

# Podział danych

```{r}
library(rsample)

set.seed(123)
credit_split <- validation_split(data = credit, strata = "risk")

credit_train <- training(credit_split$splits[[1]])
credit_test <- assessment(credit_split$splits[[1]])

save(credit_train, credit_test, file = "data/credit_train_test.rda")

table(credit_train$risk)
table(credit_test$risk)

```

# Drzewo decyzyjne

```{r}
library(rpart)
library(rpart.plot)

m1 <- rpart(risk ~ ., data = credit_train)

rpart.plot(m1)
```
```{r}
library(caret)

credit_train_m1 <- predict(m1, credit_train, type="class")

table(credit_train$risk, credit_train_m1)

confusionMatrix(data = credit_train_m1, reference = credit_train$risk, 
                mode = "everything", positive = "good")
```

```{r}
credit_test_m1 <- predict(m1, credit_test, type="class")

confusionMatrix(data = credit_test_m1, reference = credit_test$risk, 
                mode = "everything", positive = "good")
159*(3500*0.2)-16*(3500*0.5)
```

# Lasy losowe

```{r}
library(ranger)

m2 <- ranger(risk ~ ., data = credit_train, num.trees = 10)

credit_train_m2 <- predict(m2, credit_train)

confusionMatrix(data = credit_train_m2$predictions, reference = credit_train$risk,
                mode = "everything", positive = "good")
```
```{r}
credit_test_m2 <- predict(m2, credit_test)

confusionMatrix(data = credit_test_m2$predictions, reference = credit_test$risk,
                mode = "everything", positive = "good")
139*(3500*0.2)-36*(3500*0.5)
```

# Gradient boosting

```{r}
library(h2o)

h2o.init()

credit_train_h2o <- as.h2o(credit_train)
credit_test_h2o <- as.h2o(credit_test)

x_vars <- names(credit_train)[-10]

m3 <- h2o.gbm(x = x_vars, y = "risk", training_frame = credit_train_h2o)
m3
```

```{r}
credit_train_m3 <- as.data.frame(h2o.predict(m3, credit_train_h2o))

confusionMatrix(data = credit_train_m3$predict, reference = credit_train$risk,
                mode = "everything", positive = "good")
```

```{r}
credit_test_m3 <- as.data.frame(h2o.predict(m3, credit_test_h2o))

confusionMatrix(data = credit_test_m3$predict, reference = credit_test$risk,
                mode = "everything", positive = "good")
142*(3500*0.2)-33*(3500*0.5)
```

```{r}
plot(h2o.performance(m3), type="roc")
```

```{r}
h2o.varimp(m3)
```

```{r}
h2o.partialPlot(object = m3, data = credit_test_h2o, cols = "credit_amount")
```

```{r}
h2o.partialPlot(object = m3, data = credit_test_h2o, cols = "purpose")
```